### ISSUE TITLE
Error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by mohamad-d-zz** [jaleelx98/Rambo-Bot#2]
? [>] Insert Username: *************
? [>] Insert Password: ************
? [>] Insert Hashtag: ************
? [>] Number of Accounts per Delay: 5
? [>] Insert Sleep (In MiliSeconds) 900000

 [?] Try to Login . . .
(node:2597) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:2597) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Error: Error: read ECONNRESET
    at /Users/**********/Downloads/Rambo-Bot-main/node_modules/instagram-private-api/dist/core/session.js:156:19
    at tryCatcher (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/**********/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by mohamad-d-zz** [comment]
and sometimes this error:

[?] Try to Login . . .
(node:11100) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:11100) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[!] Login Success!
 [?] Like and Comment All Account In Hashtag: #--------
(node:11100) UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET
    at /Users/--------/Downloads/Rambo-Bot-main/node_modules/instagram-private-api/dist/core/request.js:288:19
    at tryCatcher (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/s--------d/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
(node:11100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
RequestError: Error: read ECONNRESET
    at /Users/--------/Downloads/Rambo-Bot-main/node_modules/instagram-private-api/dist/core/request.js:288:19
    at tryCatcher (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/--------/Downloads/Rambo-Bot-main/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21) {
  json: RequestError: Error: read ECONNRESET
      at new RequestError (/Users/--------/Downloads/Rambo-Bot-main/node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (/Users/--------/Downloads/Rambo-Bot-main/node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (/Users/--------/Downloads/Rambo-Bot-main/node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (/Users/--------/Downloads/Rambo-Bot-main/node_modules/request/request.js:185:22)
      at Request.emit (events.js:314:20)
      at Request.onRequestError (/Users/--------/Downloads/Rambo-Bot-main/node_modules/request/request.js:881:8)
      at ClientRequest.emit (events.js:314:20)
      at TLSSocket.socketErrorListener (_http_client.js:428:9)
      at TLSSocket.emit (events.js:314:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    cause: Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:208:20) {
      errno: 'ECONNRESET',
      code: 'ECONNRESET',
      syscall: 'read'
    },
    error: Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:208:20) {
      errno: 'ECONNRESET',
      code: 'ECONNRESET',
      syscall: 'read'
    },
    options: {
      method: 'GET',
      url: 'https://i.instagram.com/api/v1/feed/tag/%D8%A7%D8%B3%D8%AA%D8%A7%D8%B1%D8%AA%D8%A7%D9%BE/?rank_token=a9756f1a-be52-5576-8523-db71c8d78825',
      resolveWithFullResponse: true,
      headers: [Object],
      gzip: true,
      jar: [RequestJar],
      callback: [Function: RP$callback],
      transform: undefined,
      simple: true,
      transform2xxOnly: false
    },
    response: undefined
  }
}
